image:
  name: gcr.io/kaniko-project/executor:v1.23.2-debug
  entrypoint: [""]

stages:
  - build image

build-image:
  stage: build image
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$(echo -n $CI_DEPENDENCY_PROXY_SERVER | awk -F[:] '{print $1}')\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --verbosity=info --skip-tls-verify --context ${CI_PROJECT_DIR} --destination "${CI_REGISTRY_IMAGE}/hello:gitlab-$CI_COMMIT_SHORT_SHA"
